
version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Pre
          command: sh scripts/createCredentials.sh
      - run:
          name: Export
          command: export AZURE_AUTH_LOCATION=/tmp/credsINT.json
      - run:
          name: Test
          command: export
