
version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Pre
          command: sh scripts/createCredentials.sh
      - run:
          name: Export
          command: echo 'export AZURE_AUTH_LOCATION=${outputPathCredsfile}' >> $BASH_ENV
      - run:
          name: Test
          command: export
